PROGRAM = nut

PROGRAM_SOURCES = sq.cpp

PROGRAM_INCLUDES = -I. -I../squirrel -I../sqstdlib

PROGRAM_LDFLAGS = -L../squirrel -L../sqstdlib

PROGRAM_LIBS = -lsquirrel -lsqstdlib

include ../../Makefile.inc
