LIBRARY = libsquirrel.a

LIBRARY_SOURCES = \
	sqapi.cpp \
	sqbaselib.cpp \
	sqclass.cpp \
	sqcompiler.cpp \
	sqdebug.cpp \
	sqfuncstate.cpp \
	sqlexer.cpp \
	sqmem.cpp \
	sqobject.cpp \
	sqstate.cpp \
	sqtable.cpp \
	sqvm.cpp

LIBRARY_INCLUDES = -I.

include ../../Makefile.inc
